### ISSUE TITLE
Make the pencil edit icon configurable for the Ember template

### ISSUE THREAD

**Issue by jenweber** [empress/guidemaker#3]
Right now, it always points to the Ember.js Guides.

This work may already be done, and possibly just needs to be put in a release.

**Comment by mansona** [comment]
This issue ended up being something that is governed by the **template** rather than the guidemaker core 👍 

I would have moved it to the guidemaker-ember-template but apparently this new "transfer issue" beta functionality doesn't work between organisations 🤔 oh well 😂
